FROM openjdk:17
VOLUME /tmp
COPY contact-client/target/*.jar app.jar

ARG otel_java_agent_version=v1.24.0

ADD https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/${otel_java_agent_version}/opentelemetry-javaagent.jar /opentelemetry-javaagent.jar

ENTRYPOINT ["java","-javaagent:/opentelemetry-javaagent.jar","-Dotel.javaagent.logging=application","-Dotel.traces.exporter=none","-Dotel.metrics.exporter=prometheus","-jar","/app.jar"]