apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
  - image: us-central1-docker.pkg.dev/m2c-demo/container/contact-server
    docker:
      dockerfile: Dockerfile-server
    sync:
      auto: false
  - image: us-central1-docker.pkg.dev/m2c-demo/container/contact-client
    docker:
      dockerfile: Dockerfile-client
    sync:
      auto: false
  googleCloudBuild: {}
    
deploy:
  kustomize:
    paths:
    - k8s

