apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-client
  labels:
    app: contact-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-client
  template:
    metadata:
      labels:
        app: contact-client
    spec:
      containers:
      - name: contact-client
        imagePullPolicy: Always
        image: us-central1-docker.pkg.dev/m2c-demo/container/contact-client
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /api-key.json
        - name: GOOGLE_CLOUD_PROJECT
          value: m2c-demo
        - name: OTEL_TRACES_EXPORTER
          value: google_cloud_trace
        - name: OTEL_METRICS_EXPORTER
          value: google_cloud_monitoring
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
        volumeMounts:
        - mountPath: /api-key.json
          name: api-key
          readOnly: true
      volumes:
      - name: api-key
        secret:
          secretName: api-key

---
apiVersion: v1
kind: Service
metadata:
  name: contact-client
spec:
  selector:
    app: contact-client
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    name: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-server
  labels:
    app: contact-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-server
  template:
    metadata:
      labels:
        app: contact-server
    spec:
      containers:
      - name: contact-server
        imagePullPolicy: Always
        image: us-central1-docker.pkg.dev/m2c-demo/container/contact-server
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /api-key.json
        - name: GOOGLE_CLOUD_PROJECT
          value: m2c-demo
        - name: OTEL_TRACES_EXPORTER
          value: google_cloud_trace
        - name: OTEL_METRICS_EXPORTER
          value: google_cloud_monitoring
        envFrom:
        - secretRef:
            name: contact-db-cred
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
        volumeMounts:
        - mountPath: /api-key.json
          name: api-key
          readOnly: true
      volumes:
      - name: api-key
        secret:
          secretName: api-key

---
apiVersion: v1
kind: Service
metadata:
  name: contact-server
spec:
  selector:
    app: contact-server
  ports:
  - port: 80
    targetPort: 8080
    name: web
